### ISSUE TITLE
[Bug]: Paddle.js not available at HTMLScriptElement.

### ISSUE THREAD

**Issue by rftglyv** [PaddleHQ/paddle-js-wrapper#71]
### What happened?

I'm using NextJS @^14.2.16 and I updated PaddleJs wrapper to the latest version 1.3.0. And when I build the app it can't inject PaddleJs script. 
Here's console error log:
```js
Error: Paddle.js not available at HTMLScriptElement.<anonymous> (index.esm.js:460:18) overrideMethod	@	hook.js:608
```

I downgraded version to 1.2.3 and now the wrapper works perfectly I can't understand why it happened. 
Here's my Paddle Init function :
```js
// Create a local state to store Paddle instance
    const [paddle, setPaddle] = useState();
    const [paddleEvent, setPaddleEvent] = useState();

    // Download and initialize Paddle instance from CDN
    useEffect(() => {
        initializePaddle({
            environment: 'production',
            token: process.env.NEXT_PUBLIC_PADDLE_CLIENT_API_KEY,
            checkout: {
                settings: {
                    displayMode: "overlay",
                    theme: "light",
                    locale: "en"
                }
            },
            eventCallback: function (data) {
                setPaddleEvent(data);
            }
        }).catch(error => console.error(error)).then(
            (paddleInstance) => {
                if (paddleInstance) {
                    setPaddle(paddleInstance);
                }
            },
        );
    }, []);
```

### Steps to reproduce

1. Update wrapper to latest version (1.3.0)
2. Try to initialize paddle with help of wrapper and create a local state to store Paddle instance
3. Volia. It gives such error : Error: Paddle.js not available at HTMLScriptElement.<anonymous> (index.esm.js:460:18) overrideMethod	@	hook.js:608

### What did you expect to happen?

It must download and initialize Paddle instance from CDN then store paddle instance in local state and open checkout.

### How are you integrating?

I'm using "next": "^14.2.16","react": "^18.3.1", "react-dom": "^18.3.1"

### Logs

```shell
<html>
<body>
<!--StartFragment--><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 74, 119); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Paddle.js not available
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLScriptElement.&lt;anonymous&gt; (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:3000/turbopack/[project]/node_modules/@paddle/paddle-js/dist/index.esm.js:460:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none !important; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">index.esm.js:460:18</button>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 74, 119); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; width: 402px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | overrideMethod | @ | hook.js:608
-- | -- | -- | --
  | Show less

</span></div><!--EndFragment-->
</body>
</html>
```

**Comment by vikram2000b** [comment]
We are also facing the same issue. Were you able to find any solution to this?

**Comment by rftglyv** [comment]
> We are also facing the same issue. Were you able to find any solution to this?

Unfortunately, no. I've just downgraded package and it works well now

**Comment by vifer** [comment]
@rftglyv Thank you for raising this issue, we are currently investigating what could be wrong with latest version, for now we recommend to downgrade package (v 1.2.3) if you are facing this issue, sorry about any inconvenience this might cause.

**Comment by rftglyv** [comment]
> @rftglyv Thank you for raising this issue, we are currently investigating what could be wrong with latest version, for now we recommend to downgrade package (v 1.2.3) if you are facing this issue, sorry about any inconvenience this might cause.

Thanks for your attention. I'm waiting for the future stable update.

**Comment by danbillson** [comment]
Thank you for reporting this issue! We will look into it and provide an update soon.

**Comment by danbillson** [comment]
Apologies, the release of 1.3.0 was a little premature and has some underlying dependencies that haven't been released yet. Please continue to use 1.2.3 in the mean time
